### ISSUE TITLE
build: hello world 배포

### ISSUE THREAD

**Issue by anjm1020** [MinSaMo/sms_server#2]
### Description
CI/CD, Docker, build.gradle로 hello world 서버 배포

### TODO
- [x] build.gradle 설정 (빌드 파일 이름)
- [x] docker 배포 방식 설정
- docker-compose로 한번에 배포?
- 만약에 docker-compose로 배포한다면, 그냥 내 webApp만 따로 빌드해서 올릴 수는 없을까?
- [x] CI 스크립트 작성, CD 스크립트 작성
- .env 또는 yml secret 전략 정하기
- CI 통과되어야 CD 되도록
> `Nov4` 일단 CI/CD 한번에 올려놓음
- [x] test 환경 구축
